[package]
name = "aliexpress-sdk"
version = "1.0.0"
edition = "2021"

[dependencies]
hmac = "0.13.0-pre.4"
sha2 = "0.11.0-pre.4"
serde_json = "1.0.128"
reqwest = { version = "0.12.7", features = ["json"] }
hex = "0.4.3"
chrono = "0.4.38"
